// <auto-generated />
namespace TodoApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class todoIliskiUpdateMigration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(todoIliskiUpdateMigration2));
        
        string IMigrationMetadata.Id
        {
            get { return "202109051719005_todoIliskiUpdateMigration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
